"""Build the release: standalone ZIP and MSI installer.

Usage:  python tools/release.py [--skip-tests] [--skip-build] [--skip-zip] [--skip-msi]

Output (release/<version>/):
    VoiceCleaner-<v>-win64-portable.zip   unzip anywhere and run VoiceCleaner.exe
    VoiceCleaner-<v>-win64-installer/     VoiceCleaner-<v>.msi + vc1.cab, vc2.cab, ...
                                          (the cabinets must stay next to the .msi)
    VoiceCleaner-<v>-win64-installer.zip  the installer folder as one download
    SHA256SUMS.txt

Requires the WiX tool from the repo's tool manifest: ``dotnet tool restore``.
"""
from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.utils.config import APP_VERSION  # noqa: E402

DIST = ROOT / "dist" / "VoiceCleaner"
OUT = ROOT / "release" / APP_VERSION
WIX_DIR = ROOT / "packaging" / "wix"


def run(*cmd, cwd=ROOT):
    print(">", " ".join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], cwd=cwd, check=True)


def version_tuple() -> tuple[int, int, int, int]:
    parts = [int(p) for p in APP_VERSION.split(".")[:4]]
    return tuple(parts + [0] * (4 - len(parts)))  # type: ignore[return-value]


def write_version_info():
    v = version_tuple()
    text = f"""# UTF-8 - generated by tools/release.py
VSVersionInfo(
  ffi=FixedFileInfo(filevers={v}, prodvers={v}, mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
                    date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Steamburger Studios'),
      StringStruct('FileDescription', 'VoiceCleaner - speech cleanup and enhancement'),
      StringStruct('FileVersion', '{APP_VERSION}'),
      StringStruct('InternalName', 'VoiceCleaner'),
      StringStruct('LegalCopyright', 'Steamburger Studios'),
      StringStruct('OriginalFilename', 'VoiceCleaner.exe'),
      StringStruct('ProductName', 'VoiceCleaner'),
      StringStruct('ProductVersion', '{APP_VERSION}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    (ROOT / "build").mkdir(exist_ok=True)
    (ROOT / "build" / "version_info.txt").write_text(text, encoding="utf-8")


README = """VoiceCleaner {v}  -  by Steamburger Studios
https://www.steamburgerstudios.com/

Speech cleanup and enhancement for WAV recordings: noise and room reduction,
neural voice re-synthesis, EQ, leveling and loudness, recording, sessions and
playback. Works fully offline.

PORTABLE (ZIP)
  Unzip the whole folder anywhere (e.g. D:\\Apps\\VoiceCleaner) and run
  VoiceCleaner.exe. Keep the _internal and models folders next to it.

INSTALLER (MSI)
  Keep VoiceCleaner-{v}.msi and the vc*.cab files together in one folder and
  double-click the .msi. Uninstall from Settings > Apps.

REQUIREMENTS
  Windows 10/11 64-bit, 8 GB RAM (16 GB recommended for long recordings),
  about 6 GB of disk space. An NVIDIA GPU (driver 570 or newer) is used
  automatically when present; otherwise everything runs on the CPU.

WHERE THINGS GO
  Sessions (recordings and exports): Documents\\VoiceCleaner Sessions
  Preferences: %APPDATA%\\VoiceCleaner     Logs: %LOCALAPPDATA%\\VoiceCleaner\\logs

DIAGNOSTICS
  VoiceCleaner.exe --selftest input.wav output.wav    (result in the log)
  VoiceCleaner.exe --list-inputs                       (recording devices)

Third-party licenses: see the LICENSES folder.
"""


def build(skip_tests: bool):
    write_version_info()
    run(sys.executable, "tools/make_installer_art.py")
    args = [sys.executable, "tools/build_windows.py"] + (["--skip-tests"] if skip_tests else [])
    run(*args)
    (DIST / "README.txt").write_text(README.format(v=APP_VERSION), encoding="utf-8")


def make_zip() -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    zpath = OUT / f"VoiceCleaner-{APP_VERSION}-win64-portable.zip"
    files = sorted(p for p in DIST.rglob("*") if p.is_file())
    total = sum(p.stat().st_size for p in files)
    done = 0
    print(f"Zipping {len(files)} files ({total / 1e9:.2f} GB)...", flush=True)
    with zipfile.ZipFile(zpath, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6, allowZip64=True) as z:
        for i, p in enumerate(files):
            # the weights are already dense: storing saves minutes and costs almost nothing
            ctype = zipfile.ZIP_STORED if p.suffix in (".pt", ".ckpt", ".best") else zipfile.ZIP_DEFLATED
            z.write(p, Path("VoiceCleaner") / p.relative_to(DIST), compress_type=ctype)
            done += p.stat().st_size
            if i % 200 == 0:
                print(f"  {done / total:5.1%}", flush=True)
    print(f"  -> {zpath.name} ({zpath.stat().st_size / 1e9:.2f} GB)")
    return zpath


def make_msi() -> Path:
    inst = OUT / f"VoiceCleaner-{APP_VERSION}-win64-installer"
    if inst.exists():
        shutil.rmtree(inst)
    inst.mkdir(parents=True)
    msi = inst / f"VoiceCleaner-{APP_VERSION}.msi"
    run("dotnet", "tool", "restore")
    for ext in ("WixToolset.UI.wixext/5.0.2", "WixToolset.Util.wixext/5.0.2"):
        run("dotnet", "tool", "run", "wix", "extension", "add", ext)
    run("dotnet", "tool", "run", "wix", "build",
        WIX_DIR / "VoiceCleaner.wxs", WIX_DIR / "InstallDirUI.wxs",
        "-ext", "WixToolset.UI.wixext", "-ext", "WixToolset.Util.wixext",
        "-arch", "x64",
        "-d", f"Version={APP_VERSION}",
        "-d", f"SourceDir={DIST}",
        "-d", f"IconFile={ROOT / 'assets' / 'voicecleaner.ico'}",
        "-d", f"BannerBmp={WIX_DIR / 'banner.bmp'}",
        "-d", f"DialogBmp={WIX_DIR / 'dialog.bmp'}",
        "-intermediateFolder", ROOT / "build" / "wix",
        "-o", msi)
    for junk in inst.glob("*.wixpdb"):
        junk.unlink()
    shutil.copy(DIST / "README.txt", inst / "README.txt")
    size = sum(p.stat().st_size for p in inst.iterdir())
    print(f"  -> {inst.name}: {', '.join(p.name for p in sorted(inst.iterdir()))} ({size / 1e9:.2f} GB)")
    return inst


def zip_installer(inst: Path) -> Path:
    zpath = OUT / f"{inst.name}.zip"
    with zipfile.ZipFile(zpath, "w", compression=zipfile.ZIP_STORED, allowZip64=True) as z:  # cabs are compressed
        for p in sorted(inst.iterdir()):
            z.write(p, Path(inst.name) / p.name)
    print(f"  -> {zpath.name} ({zpath.stat().st_size / 1e9:.2f} GB)")
    return zpath


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 22), b""):
            h.update(block)
    return h.hexdigest()


def write_checksums():
    lines = []
    for p in sorted(OUT.rglob("*")):
        if p.is_file() and p.name != "SHA256SUMS.txt":
            lines.append(f"{sha256(p)}  {p.relative_to(OUT).as_posix()}")
    (OUT / "SHA256SUMS.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


def main():
    a = set(sys.argv[1:])
    if "--skip-build" not in a:
        build("--skip-tests" in a)
    OUT.mkdir(parents=True, exist_ok=True)
    if "--skip-zip" not in a:
        make_zip()
    if "--skip-msi" not in a:
        zip_installer(make_msi())
    write_checksums()
    print(f"\nRelease {APP_VERSION} ready in {OUT}")


if __name__ == "__main__":
    main()
