"""Build and (optionally) publish a VoiceCleaner release.

Usage:
    python tools/release.py [--skip-tests] [--skip-build] [--only standard|gpu]
    python tools/release.py --publish-only          # upload an already built release

Every file fits GitHub's 2 GB per-file release limit. Output (release/<version>/, flat,
uploaded as-is to the GitHub release v<version>):

  Standard edition (CPU, works on every PC)
    VoiceCleaner-<v>-win64.msi                    single-file installer
    VoiceCleaner-<v>-win64-portable.zip           unzip and run
  NVIDIA GPU edition
    VoiceCleaner-GPU-<v>-web.exe                  web installer: downloads the files below
    VoiceCleaner-GPU-<v>-win64.msi + vcgpu*.cab   installer (cabinets must sit next to it)
    VoiceCleaner-GPU-<v>-win64-portable.zip.001   split portable ZIP (open .001 with 7-Zip,
    VoiceCleaner-GPU-<v>-win64-portable.zip.002   or join with copy /b and unzip)
  SHA256SUMS.txt, RELEASE_NOTES.md

Neither edition bundles the 490 MB voice re-synthesis model; the app downloads it
on demand. Requires: .venv (CUDA PyTorch), .venv-cpu (CPU PyTorch), `dotnet tool
restore` (WiX 5), and for publishing an authenticated GitHub CLI (`gh auth login`).
"""
from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

from app.utils.config import APP_VERSION  # noqa: E402
from build_windows import DEFAULT_PYTHON, build, dist_dir  # noqa: E402

REPO = "BuddyDoQ/VoiceCleaner"
TAG = f"v{APP_VERSION}"
OUT = ROOT / "release" / APP_VERSION
WIX_DIR = ROOT / "packaging" / "wix"
PART_SIZE = 1_900_000_000  # below GitHub's 2 GiB per-file limit
GH = shutil.which("gh") or r"C:\Program Files\GitHub CLI\gh.exe"


def run(*cmd, cwd=ROOT):
    print(">", " ".join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], cwd=cwd, check=True)


def name(edition: str, suffix: str) -> str:
    prefix = "VoiceCleaner-GPU" if edition == "gpu" else "VoiceCleaner"
    return f"{prefix}-{APP_VERSION}-{suffix}"


# --- build ----------------------------------------------------------------------------
def write_version_info():
    v = tuple(([int(p) for p in APP_VERSION.split(".")] + [0, 0, 0, 0])[:4])
    text = f"""# UTF-8 - generated by tools/release.py
VSVersionInfo(
  ffi=FixedFileInfo(filevers={v}, prodvers={v}, mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
                    date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Steamburger Studios'),
      StringStruct('FileDescription', 'VoiceCleaner - speech cleanup and enhancement'),
      StringStruct('FileVersion', '{APP_VERSION}'),
      StringStruct('InternalName', 'VoiceCleaner'),
      StringStruct('LegalCopyright', 'Steamburger Studios. MIT License.'),
      StringStruct('OriginalFilename', 'VoiceCleaner.exe'),
      StringStruct('ProductName', 'VoiceCleaner'),
      StringStruct('ProductVersion', '{APP_VERSION}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    (ROOT / "build").mkdir(exist_ok=True)
    (ROOT / "build" / "version_info.txt").write_text(text, encoding="utf-8")


README = """VoiceCleaner {v}{ed_title}  -  by Steamburger Studios
https://www.steamburgerstudios.com/   |   https://github.com/{repo}

Speech cleanup and enhancement for WAV recordings: noise and room reduction,
neural voice re-synthesis, EQ, leveling and loudness, recording, sessions and
playback. Works offline.

EDITION
  {ed_text}

FIRST USE OF VOICE RE-SYNTHESIS
  The 490 MB re-synthesis model is downloaded once, from NVIDIA's official
  repository, when you first use the feature (Voice Re-synthesis section). It is
  stored in %LOCALAPPDATA%\\VoiceCleaner\\models. Everything else works offline.

REQUIREMENTS
  Windows 10/11 64-bit, 8 GB RAM (16 GB recommended for long recordings).

WHERE THINGS GO
  Sessions (recordings and exports): Documents\\VoiceCleaner Sessions
  Preferences: %APPDATA%\\VoiceCleaner     Logs: %LOCALAPPDATA%\\VoiceCleaner\\logs

DIAGNOSTICS
  VoiceCleaner.exe --selftest input.wav output.wav    (result in the log)
  VoiceCleaner.exe --list-inputs                       (recording devices)

License: MIT (see LICENSES). Third-party licenses: see the LICENSES folder.
"""
ED_TEXT = {
    "standard": "Standard: runs on any PC using the CPU. For faster processing on NVIDIA\n"
                "  graphics cards, install the NVIDIA GPU edition instead.",
    "gpu": "NVIDIA GPU: uses an NVIDIA graphics card (driver 570 or newer) when present,\n"
           "  otherwise the CPU. Needs about 5 GB of disk space.",
}


def build_edition(edition: str, skip_tests: bool) -> Path:
    py = DEFAULT_PYTHON[edition]
    if not py.exists():
        sys.exit(f"Missing {py}. Create the venv for the {edition} edition first (see README).")
    dist = build(edition, py, skip_tests)
    (dist / "README.txt").write_text(README.format(
        v=APP_VERSION, repo=REPO, ed_title=" (NVIDIA GPU edition)" if edition == "gpu" else "",
        ed_text=ED_TEXT[edition]), encoding="utf-8")
    return dist


# --- packaging ---------------------------------------------------------------------------
def make_zip(edition: str) -> list[Path]:
    dist = dist_dir(edition)
    zpath = OUT / name(edition, "win64-portable.zip")
    files = sorted(p for p in dist.rglob("*") if p.is_file())
    print(f"Zipping {edition}: {len(files)} files ({sum(p.stat().st_size for p in files) / 1e9:.2f} GB)", flush=True)
    with zipfile.ZipFile(zpath, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6, allowZip64=True) as z:
        for p in files:
            z.write(p, Path("VoiceCleaner") / p.relative_to(dist))
    if zpath.stat().st_size <= PART_SIZE:
        return [zpath]
    return split_file(zpath)


def split_file(path: Path) -> list[Path]:
    """Raw byte split (name.001, .002, ...): 7-Zip opens .001 directly; or `copy /b` to join."""
    parts = []
    with open(path, "rb") as f:
        i = 1
        while True:
            chunk_path = path.with_name(f"{path.name}.{i:03d}")
            written = 0
            with open(chunk_path, "wb") as out:
                while written < PART_SIZE:
                    block = f.read(min(1 << 24, PART_SIZE - written))
                    if not block:
                        break
                    out.write(block)
                    written += len(block)
            if written == 0:
                chunk_path.unlink()
                break
            parts.append(chunk_path)
            i += 1
    path.unlink()
    print(f"  split into {len(parts)} parts: {', '.join(p.name for p in parts)}")
    return parts


def wix(*args):
    run("dotnet", "tool", "run", "wix", *args)


def make_msi(edition: str) -> Path:
    msi = OUT / name(edition, "win64.msi")
    wix("build", WIX_DIR / "VoiceCleaner.wxs", WIX_DIR / "InstallDirUI.wxs",
        "-ext", "WixToolset.UI.wixext", "-ext", "WixToolset.Util.wixext", "-arch", "x64",
        "-d", f"Edition={edition}", "-d", f"Version={APP_VERSION}", "-d", f"SourceDir={dist_dir(edition)}",
        "-d", f"IconFile={ROOT / 'assets' / 'voicecleaner.ico'}",
        "-d", f"BannerBmp={WIX_DIR / 'banner.bmp'}", "-d", f"DialogBmp={WIX_DIR / 'dialog.bmp'}",
        "-intermediateFolder", ROOT / "build" / f"wix-{edition}", "-o", msi)
    for junk in OUT.glob("*.wixpdb"):
        junk.unlink()
    return msi


def make_web_installer(gpu_msi: Path) -> Path:
    exe = OUT / name("gpu", "web.exe")
    wix("build", WIX_DIR / "Bundle.wxs", "-ext", "WixToolset.BootstrapperApplications.wixext", "-arch", "x64",
        "-d", f"Version={APP_VERSION}", "-d", f"MsiFile={gpu_msi}",
        "-d", f"BaseUrl=https://github.com/{REPO}/releases/download/{TAG}/",
        "-d", f"IconFile={ROOT / 'assets' / 'voicecleaner.ico'}",
        "-d", f"LogoFile={WIX_DIR / 'bundle_logo.png'}",
        "-intermediateFolder", ROOT / "build" / "wix-bundle", "-o", exe)
    for junk in OUT.glob("*.wixpdb"):
        junk.unlink()
    return exe


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 22), b""):
            h.update(block)
    return h.hexdigest()


def write_checksums():
    lines = [f"{sha256(p)}  {p.name}" for p in sorted(OUT.iterdir())
             if p.is_file() and p.name != "SHA256SUMS.txt" and not p.name.startswith("RELEASE_NOTES")]
    (OUT / "SHA256SUMS.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_notes():
    def size(pattern):
        total = sum(p.stat().st_size for p in OUT.glob(pattern))
        return f"{total / 1e9:.2f} GB" if total > 1e9 else f"{total / 1e6:.0f} MB"

    v = APP_VERSION
    notes = f"""## VoiceCleaner {v} by [Steamburger Studios](https://www.steamburgerstudios.com/)

Speech cleanup and enhancement for WAV recordings: noise and room reduction, neural voice
re-synthesis, EQ and tonal balancing, dynamic leveling, loudness, recording (microphone and
desktop audio), sessions and playback. Works offline.

### Which download?

| | Download | Size |
|---|---|---|
| **Most PCs** (standard, CPU) | [`VoiceCleaner-{v}-win64.msi`](https://github.com/{REPO}/releases/download/{TAG}/VoiceCleaner-{v}-win64.msi) (installer) | {size(f"VoiceCleaner-{v}-win64.msi")} |
| | `VoiceCleaner-{v}-win64-portable.zip` (no install) | {size(f"VoiceCleaner-{v}-win64-portable.zip")} |
| **NVIDIA graphics card** (faster) | [`VoiceCleaner-GPU-{v}-web.exe`](https://github.com/{REPO}/releases/download/{TAG}/VoiceCleaner-GPU-{v}-web.exe): small installer that downloads the rest | {size(f"VoiceCleaner-GPU-{v}-web.exe")} (downloads {size("vcgpu*.cab")}) |
| | `VoiceCleaner-GPU-{v}-win64-portable.zip.001` + `.002` (no install) | {size(f"VoiceCleaner-GPU-{v}-win64-portable.zip.*")} |

- **Voice re-synthesis model:** the 490 MB model is downloaded once, from NVIDIA's
  official repository, the first time you use Voice Re-synthesis. Everything else works
  offline.
- **Standard vs GPU:** both editions install to the same place, and installing one
  replaces the other.
- **GPU portable ZIP:** open the `.001` file with [7-Zip](https://www.7-zip.org/). Or join
  the parts in a command prompt with `copy /b VoiceCleaner-GPU-{v}-win64-portable.zip.001
  + VoiceCleaner-GPU-{v}-win64-portable.zip.002 VoiceCleaner-GPU.zip`, then unzip.
- **GPU installer without the web installer:** download the `VoiceCleaner-GPU-{v}-win64.msi`
  and every `vcgpu*.cab` file into one folder, then run the `.msi`.
- **Unsigned builds:** Windows SmartScreen may warn on first run. Choose *More info* →
  *Run anyway*. Verify downloads with `SHA256SUMS.txt`.

Requirements: Windows 10/11 64-bit, 8 GB RAM. GPU edition: NVIDIA driver 570 or newer.
"""
    changes = changelog_entry(APP_VERSION)
    if changes:
        title, rest = notes.split("\n", 1)
        notes = f"{title}\n\n### What's new in {APP_VERSION}\n\n{changes}\n{rest}"
    (OUT / "RELEASE_NOTES.md").write_text(notes, encoding="utf-8")


def changelog_entry(version: str) -> str:
    """The CHANGELOG.md section for ``version`` (without its heading)."""
    try:
        text = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    except OSError:
        return ""
    import re

    m = re.search(rf"^## {re.escape(version)}\s*$(.*?)(?=^## |\Z)", text, flags=re.M | re.S)
    return m.group(1).strip() if m else ""


def macos_section(body: str) -> str:
    """The "## macOS ..." section (to the end) of existing release notes, or ""."""
    import re

    m = re.search(r"^## macOS\b", body.replace("\r\n", "\n"), flags=re.M)
    return body.replace("\r\n", "\n")[m.start():].strip() + "\n" if m else ""


def publish():
    assets = [p for p in sorted(OUT.iterdir()) if p.is_file() and not p.name.startswith("RELEASE_NOTES")]
    too_big = [p.name for p in assets if p.stat().st_size >= 2 * 1024**3]
    if too_big:
        sys.exit(f"Files over GitHub's 2 GB limit: {too_big}")
    run(GH, "auth", "status")
    exists = subprocess.run([GH, "release", "view", TAG, "-R", REPO], capture_output=True).returncode == 0
    if exists:
        run(GH, "release", "upload", TAG, *assets, "-R", REPO, "--clobber")
        notes = OUT / "RELEASE_NOTES.md"
        current = subprocess.run([GH, "release", "view", TAG, "-R", REPO, "--json", "body", "--jq", ".body"],
                                 capture_output=True, text=True, encoding="utf-8").stdout
        mac = macos_section(current)
        if mac:  # the Mac build is published from a Mac (tools/build_mac.py); keep its section
            notes = OUT / "RELEASE_NOTES-combined.md"
            notes.write_text((OUT / "RELEASE_NOTES.md").read_text(encoding="utf-8").rstrip() + "\n\n---\n\n" + mac,
                             encoding="utf-8")
        run(GH, "release", "edit", TAG, "-R", REPO, "--notes-file", notes)
    else:
        run(GH, "release", "create", TAG, *assets, "-R", REPO, "--target", "main",
            "--title", f"VoiceCleaner {APP_VERSION}", "--notes-file", OUT / "RELEASE_NOTES.md")
    print(f"\nPublished https://github.com/{REPO}/releases/tag/{TAG}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-tests", action="store_true")
    ap.add_argument("--skip-build", action="store_true")
    ap.add_argument("--only", choices=["standard", "gpu"])
    ap.add_argument("--publish", action="store_true", help="upload to GitHub after building")
    ap.add_argument("--publish-only", action="store_true")
    a = ap.parse_args()
    if a.publish_only:
        publish()
        return
    editions = [a.only] if a.only else ["standard", "gpu"]
    if not a.skip_build:
        write_version_info()
        run(sys.executable, "tools/make_installer_art.py")
        for i, ed in enumerate(editions):
            build_edition(ed, skip_tests=a.skip_tests or i > 0)  # run the tests once
    if OUT.exists() and not a.only:
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True, exist_ok=True)
    run("dotnet", "tool", "restore")
    for ext in ("WixToolset.UI.wixext/5.0.2", "WixToolset.Util.wixext/5.0.2",
                "WixToolset.BootstrapperApplications.wixext/5.0.2"):
        wix("extension", "add", ext)
    for ed in editions:
        make_zip(ed)
        msi = make_msi(ed)
        if ed == "gpu":
            make_web_installer(msi)
    write_checksums()
    write_notes()
    for p in sorted(OUT.iterdir()):
        print(f"  {p.stat().st_size / 1e6:9.1f} MB  {p.name}")
    print(f"\nRelease {APP_VERSION} ready in {OUT}")
    if a.publish:
        publish()


if __name__ == "__main__":
    os.chdir(ROOT)
    main()
